/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/Database/FPGA/Anlogic/Handwriting_digits_detect/al_ip/ram.v
 ** Date	:	2020 11 10
 ** TD version	:	4.6.18154
\************************************************************/

`timescale 1ns / 1ps

module ram ( 
	dia, addra, cea, clka,
	dob, addrb, clkb
);

	output [7:0] dob;


	input  [7:0] dia;
	input  [9:0] addra;
	input  [9:0] addrb;
	input  cea;
	input  clka;
	input  clkb;



	EG_LOGIC_BRAM #( .DATA_WIDTH_A(8),
				.DATA_WIDTH_B(8),
				.ADDR_WIDTH_A(10),
				.ADDR_WIDTH_B(10),
				.DATA_DEPTH_A(784),
				.DATA_DEPTH_B(784),
				.MODE("PDPW"),
				.REGMODE_A("NOREG"),
				.REGMODE_B("NOREG"),
				.WRITEMODE_A("NORMAL"),
				.WRITEMODE_B("READBEFOREWRITE"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K"),
				.INIT_FILE("NONE"),
				.FILL_ALL("00000000"))
			inst(
				.dia(dia),
				.dib({8{1'b0}}),
				.addra(addra),
				.addrb(addrb),
				.cea(cea),
				.ceb(1'b1),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(clkb),
				.wea(1'b1),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(1'b0),
				.rstb(1'b0),
				.doa(),
				.dob(dob));


endmodule