/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/Database/FPGA/Anlogic/Handwriting_digits_detect/al_ip/word/its.v
 ** Date	:	2020 11 13
 ** TD version	:	4.6.18154
\************************************************************/

`timescale 1ns / 1ps

module its ( doa, addra, clka, rsta );

	output [0:0] doa;

	input  [13:0] addra;
	input  clka;
	input  rsta;




	EG_LOGIC_BRAM #( .DATA_WIDTH_A(1),
				.ADDR_WIDTH_A(14),
				.DATA_DEPTH_A(11352),
				.DATA_WIDTH_B(1),
				.ADDR_WIDTH_B(14),
				.DATA_DEPTH_B(11352),
				.MODE("SP"),
				.REGMODE_A("NOREG"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE("its.mif"),
				.FILL_ALL("NONE"))
			inst(
				.dia({1{1'b0}}),
				.dib({1{1'b0}}),
				.addra(addra),
				.addrb({14{1'b0}}),
				.cea(1'b1),
				.ceb(1'b0),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(1'b0),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(rsta),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule